(****************************************************************
 * Identifiers of builtin function, types, etc.
 *
 * Copyright (C) 2022-2026 Intel Corporation
 * SPDX-License-Identifier: BSD-3-Clause
 ****************************************************************)

(* Functions *)

let eq_bool           = Ident.mk_fident "Std::Boolean::Eq"
let lazy_and_bool     = Ident.mk_fident "Std::Boolean::Lazy_And"
let lazy_or_bool      = Ident.mk_fident "Std::Boolean::Lazy_Or"
let ne_bool           = Ident.mk_fident "Std::Boolean::Ne"
let not_bool          = Ident.mk_fident "Std::Boolean::Not"
let strict_and_bool   = Ident.mk_fident "Std::Boolean::Strict_And"
let strict_or_bool    = Ident.mk_fident "Std::Boolean::Strict_Or"

let add_int           = Ident.mk_fident "Std::Integer::Add"
let align_int         = Ident.mk_fident "Std::Integer::Align_Down"
let cdiv_int          = Ident.mk_fident "Std::Integer::Ceiling_Divide"
let crem_int          = Ident.mk_fident "Std::Integer::Ceiling_Remainder"
let eq_int            = Ident.mk_fident "Std::Integer::Eq"
let exact_div_int     = Ident.mk_fident "builtin_exact_div_int" (* deprecated *)
let fdiv_int          = Ident.mk_fident "Std::Integer::Floor_Divide"
let frem_int          = Ident.mk_fident "Std::Integer::Floor_Remainder"
let ge_int            = Ident.mk_fident "Std::Integer::Ge"
let gt_int            = Ident.mk_fident "Std::Integer::Gt"
let is_pow2_int       = Ident.mk_fident "Std::Integer::Is_Power_Of_Two"
let le_int            = Ident.mk_fident "Std::Integer::Le"
let lt_int            = Ident.mk_fident "Std::Integer::Lt"
let max               = Ident.mk_fident "Std::Integer::Max"
let min               = Ident.mk_fident "Std::Integer::Min"
let mod_pow2_int      = Ident.mk_fident "Std::Integer::Mod_Power_Of_Two"
let mul_int           = Ident.mk_fident "Std::Integer::Multiply"
let ne_int            = Ident.mk_fident "Std::Integer::Ne"
let neg_int           = Ident.mk_fident "Std::Integer::Negate"
let pdiv_int          = Ident.mk_fident "Std::Integer::Positive_Divide"
let prem_int          = Ident.mk_fident "Std::Integer::Positive_Remainder"
let pow2_int          = Ident.mk_fident "Std::Integer::Power2"
let pow_int_int       = Ident.mk_fident "Std::Integer::Exp"
let shl_int           = Ident.mk_fident "Std::Integer::Shift_Left"
let shr_int           = Ident.mk_fident "Std::Integer::Shift_Right"
let sub_int           = Ident.mk_fident "Std::Integer::Subtract"
let zdiv_int          = Ident.mk_fident "Std::Integer::Truncated_Divide"
let zrem_int          = Ident.mk_fident "Std::Integer::Truncated_Remainder"

let add_bits          = Ident.mk_fident "Std::Bits::Add"
let add_bits_int      = Ident.mk_fident "Std::Bits::Add_int"
let and_bits          = Ident.mk_fident "Std::Bits::And"
let append_bits       = Ident.mk_fident "Std::Bits::Append"
let asr_bits          = Ident.mk_fident "Std::Bits::Shift_Right_Arithmetic_Restricted"
let cvt_bits_sint     = Ident.mk_fident "Std::Bits::Signed"
let cvt_bits_uint     = Ident.mk_fident "Std::Bits::Unsigned"
let cvt_int_bits      = Ident.mk_fident "Std::Bits::From_Integer"
let eq_bits           = Ident.mk_fident "Std::Bits::Eq"
let in_mask           = Ident.mk_fident "Std::Bits::In_Mask"
let is_ones           = Ident.mk_fident "Std::Bits::Is_All_Ones"
let is_zero           = Ident.mk_fident "Std::Bits::Is_Zero"
let length            = Ident.mk_fident "Std::Bits::Length"
let lsl_bits          = Ident.mk_fident "Std::Bits::Shift_Left_Logical_Restricted"
let lsr_bits          = Ident.mk_fident "Std::Bits::Shift_Right_Logical_Restricted"
let mask_int          = Ident.mk_fident "builtin_mask_int"
let mk_mask           = Ident.mk_fident "Std::Bits::Mk_Mask"
let mul_bits          = Ident.mk_fident "Std::Bits::Multiply"
let mul_bits_int      = Ident.mk_fident "Std::Bits::Multiply_int"
let ne_bits           = Ident.mk_fident "Std::Bits::Ne"
let not_bits          = Ident.mk_fident "Std::Bits::Not"
let notin_mask        = Ident.mk_fident "Std::Bits::Not_In_Mask"
let ones_bits         = Ident.mk_fident "Std::Bits::All_Ones"
let or_bits           = Ident.mk_fident "Std::Bits::Or"
let pow2_bits         = Ident.mk_fident "Std::Bits::Power2"
let replicate_bits    = Ident.mk_fident "Std::Bits::Repeat"
let sign_extend_bits  = Ident.mk_fident "Std::Bits::Sign_Extend"
let sub_bits          = Ident.mk_fident "Std::Bits::Subtract"
let sub_bits_int      = Ident.mk_fident "Std::Bits::Subtract_int"
let xor_bits          = Ident.mk_fident "Std::Bits::Xor"
let zero_extend_bits  = Ident.mk_fident "Std::Bits::Zero_Extend"
let zeros_bits        = Ident.mk_fident "Std::Bits::Zero"

let sintN              = Ident.mk_ident "__sint"
let eq_sintN           = Ident.mk_fident "Std::SInt::Eq"
let ne_sintN           = Ident.mk_fident "Std::SInt::Ne"
let gt_sintN           = Ident.mk_fident "Std::SInt::Gt"
let ge_sintN           = Ident.mk_fident "Std::SInt::Ge"
let le_sintN           = Ident.mk_fident "Std::SInt::Le"
let lt_sintN           = Ident.mk_fident "Std::SInt::Lt"
let add_sintN          = Ident.mk_fident "Std::SInt::Add"
let neg_sintN          = Ident.mk_fident "Std::SInt::Negate"
let sub_sintN          = Ident.mk_fident "Std::SInt::Subtract"
let shl_sintN          = Ident.mk_fident "Std::SInt::Shift_Left"
let shr_sintN          = Ident.mk_fident "Std::SInt::Shift_Right"
let mul_sintN          = Ident.mk_fident "Std::SInt::Multiply"
let exact_div_sintN    = Ident.mk_fident "builtin_exact_div_sintN" (* deprecated *)
let zdiv_sintN         = Ident.mk_fident "Std::SInt::Truncated_Divide"
let zrem_sintN         = Ident.mk_fident "Std::SInt::Truncated_Remainder"
let cdiv_sintN         = Ident.mk_fident "Std::SInt::Ceiling_Divide"
let crem_sintN         = Ident.mk_fident "Std::SInt::Ceiling_Remainder"
let fdiv_sintN         = Ident.mk_fident "Std::SInt::Floor_Divide"
let frem_sintN         = Ident.mk_fident "Std::SInt::Floor_Remainder"
let is_pow2_sintN      = Ident.mk_fident "Std::SInt::Is_Power_Of_Two"
let pow2_sintN         = Ident.mk_fident "Std::SInt::Exp2"
let align_sintN        = Ident.mk_fident "Std::SInt::Align_Down"
let mod_pow2_sintN     = Ident.mk_fident "Std::SInt::Mod_Power_Of_Two"
let cvt_sintN_bits     = Ident.mk_fident "Std::SInt::To_Bits"
let cvt_bits_ssintN    = Ident.mk_fident "Std::SInt::Signed"
let cvt_bits_usintN    = Ident.mk_fident "Std::SInt::Unsigned"
let cvt_sintN_int      = Ident.mk_fident "Std::SInt::To_Integer"
let cvt_int_sintN      = Ident.mk_fident "Std::SInt::From_Integer"
let resize_sintN       = Ident.mk_fident "Std::SInt::Resize"

let print_bits_hex     = Ident.mk_fident "Std::Print::Bits::Hex"
let print_boolean      = Ident.mk_fident "Std::Print::Boolean"
let print_char         = Ident.mk_fident "Std::Print::Char"
let print_int_dec      = Ident.mk_fident "Std::Print::Integer::Dec"
let print_int_hex      = Ident.mk_fident "Std::Print::Integer::Hex"
let print_sintN_dec    = Ident.mk_fident "Std::Print::SInt::Dec"
let print_sintN_hex    = Ident.mk_fident "Std::Print::SInt::Hex"
let print_str          = Ident.mk_fident "Std::Print::String"
let print              = Ident.mk_fident "Std::Print"

let info               = Ident.mk_fident "Std::Info"

let eq_enum           = Ident.mk_fident "builtin_eq_enum"
let ne_enum           = Ident.mk_fident "builtin_ne_enum"
let frem_bits_int     = Ident.mk_fident "builtin_frem_bits_int"
let ram_init          = Ident.mk_fident "Std::RAM::Init"
let ram_read          = Ident.mk_fident "Std::RAM::Read"
let ram_write         = Ident.mk_fident "Std::RAM::Write"

let boolean_ident     = Ident.mk_ident "Boolean"
let integer_ident     = Ident.mk_ident "Integer"
let string_ident      = Ident.mk_ident "String"
let bits_ident        = Ident.mk_ident "Bits"
let slice_ident       = Ident.mk_ident "Std::Slice"
let wildcard_ident    = Ident.mk_ident "_"
let dash_ident        = Ident.mk_ident "-"
let ram               = Ident.mk_ident "Std::RAM"
let true_ident        = Ident.mk_ident "True"
let false_ident       = Ident.mk_ident "False"

(* FFI support *)
let cint_type         = Ident.mk_ident "Builtin::Foreign::CInt"
let uints_type        = Ident.mk_ident "Builtin::Foreign::UInts"
let uint_type         = Ident.mk_ident "Builtin::Foreign::UInt"
let sint_type         = Ident.mk_ident "Builtin::Foreign::UInt"
let int_type          = Ident.mk_ident "Builtin::Foreign::Int"

let cint_to_integer   = Ident.mk_fident "Builtin::Foreign::CInt::To_Integer"
let cint_from_integer = Ident.mk_fident "Builtin::Foreign::CInt::From_Integer"
let uints_to_bits     = Ident.mk_fident "Builtin::Foreign::UInts::To_Bits"
let uints_from_bits   = Ident.mk_fident "Builtin::Foreign::UInts::From_Bits"
let uint_to_bits      = Ident.mk_fident "Builtin::Foreign::UInt::To_Bits"
let uint_from_bits    = Ident.mk_fident "Builtin::Foreign::UInt::From_Bits"
let uint_to_integer   = Ident.mk_fident "Builtin::Foreign::UInt::To_Integer"
let uint_from_integer = Ident.mk_fident "Builtin::Foreign::UInt::From_Integer"
let sint_to_integer   = Ident.mk_fident "Builtin::Foreign::SInt::To_Integer"
let sint_from_integer = Ident.mk_fident "Builtin::Foreign::SInt::From_Integer"
let int_to_integer    = Ident.mk_fident "Builtin::Foreign::Int::To_Integer"
let int_from_integer  = Ident.mk_fident "Builtin::Foreign::Int::From_Integer"

let asl_reset                = Ident.mk_fident "ASL_Reset"
let asl_step                 = Ident.mk_fident "ASL_Step"
let asl_get_pc               = Ident.mk_fident "ASL_GetPC"
let asl_set_pc               = Ident.mk_fident "ASL_SetPC"
let asl_elf_write_memory8    = Ident.mk_fident "ASL_WriteMemory8"

let asl_fake_return_value    = Ident.mk_ident "builtin_fake_return_value"
let asl_error_unmatched_case = Ident.mk_fident "builtin_error_unmatched_case"
let asl_end_execution        = Ident.mk_fident "Std::End_Execution"
let asl_fuzz                 = Ident.mk_fident "builtin_fuzz"

(* deprecated *)
let trace_next            = Ident.mk_fident "__TraceNext"
let trace_physical_memory = Ident.mk_fident "__TracePhysicalMemory"
let trace_virtual_memory  = Ident.mk_fident "__TraceVirtualMemory"
let trace_page_table_walk = Ident.mk_fident "__TracePageTableWalk"
let trace_error           = Ident.mk_fident "__TraceError"
let trace_event           = Ident.mk_fident "__TraceEvent"

(* deprecated *)
let old_bits_ident    = Ident.mk_ident "bits" (* deprecated *)
let old_integer_ident = Ident.mk_ident "integer" (* deprecated *)

(****************************************************************
 * End
 ****************************************************************)
