name: pull-request

on:
  pull_request:
  workflow_dispatch:

permissions: read-all

env:
  OPAMROOT: ${{ github.workspace }}/.opam

jobs:
  test:
    runs-on: ubuntu-22.04

    steps:
      - name: Check out
        uses: actions/checkout@v6
        with:
          submodules: recursive

      - name: Setup OCaml
        uses: ocaml/setup-ocaml@v3
        with:
          ocaml-compiler: 5

      - name: Install APT dependencies
        run: |
          sudo apt update
          sudo apt-get install -y libgmp-dev opam pkg-config lsb-release wget software-properties-common gnupg

      - name: Install Clang 16
        run: |
          wget https://apt.llvm.org/llvm.sh
          chmod +x llvm.sh
          sudo ./llvm.sh 16

      - name: Install Python dependencies
        run: python3 -m pip install --no-deps --require-hashes --requirement requirements.txt

      - name: Install OCaml tools and libraries
        run: |
          opam init --no-setup --disable-sandboxing
          opam switch create 5.4.1
          eval $(opam env --switch=5.4.1)
          opam install . --deps-only --with-test --with-doc --locked --yes

      - name: Build
        run: |
          eval $(opam env)
          make build

      - name: Test
        run: |
          eval $(opam env)
          make test

      - name: Build documentation
        run: |
          eval $(opam env)
          make doc
